import { StyleSheet } from 'react-native';
import { theme } from '../../src/config/theme';

export default StyleSheet.create({
  backgroundImage: {
    flex: 1,
    backgroundColor: '#ffffff02', // Keep background base white
  },
  backgroundImageStyle: {
    opacity: 0.12, // Lower opacity for a clean, non-distracting background watermark
  },
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: 32,
  },
  // 1. Branding Header Panel
  headerPanel: {
    backgroundColor: 'transparent',
    paddingTop: 48,
    paddingBottom: 16,
    paddingHorizontal: 28,
    alignItems: 'center',
  },
  Logo: {
    height: 160,
    width: 180,
    resizeMode: 'contain',
    marginBottom: -16,
  },
  title: {
    fontSize: 22,
    fontFamily: theme.fonts.bold,
    color: theme.colors.primary,
    letterSpacing: 0.2,
  },
  subtitle: {
    fontSize: 10,
    fontFamily: theme.fonts.extraBold,
    color: theme.colors.accent,
    letterSpacing: 2,
    marginTop: 2,
    textTransform: 'uppercase',
  },
  supportingText: {
    fontSize: 12,
    fontFamily: theme.fonts.regular,
    color: theme.colors.textMuted,
    textAlign: 'center',
    lineHeight: 18,
    marginTop: 8,
    maxWidth: 280,
  },
  // Form Area Wrapper
  formArea: {
    paddingHorizontal: 24,
    gap: 16,
  },
  // 2. Segmented Authentication Method Selector
  selectorContainer: {
    backgroundColor: '#E6ECF5', 
    borderRadius: 14,
    padding: 4,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  selectorButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectorButtonActive: {
    backgroundColor: theme.colors.primary, 
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  selectorText: {
    fontSize: 11,
    fontFamily: theme.fonts.bold,
    color: '#627D98', 
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  selectorTextActive: {
    color: theme.colors.white, 
  },
  // 3. Form Surface (Crisp White Card)
  formCard: {
    backgroundColor: theme.colors.white, 
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 20,
    gap: 16,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 3,
  },
  inputGroup: {
    gap: 6,
  },
  label: {
    fontSize: 9,
    fontFamily: theme.fonts.extraBold,
    color: theme.colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  // Input container with left/right icons
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D0D7E2', 
    borderRadius: 12,
    backgroundColor: theme.colors.white,
    height: 52, 
    paddingHorizontal: 16,
  },
  inputField: {
    flex: 1,
    height: '100%',
    color: theme.colors.primary,
    fontSize: 14,
    fontFamily: theme.fonts.regular,
    paddingHorizontal: 8,
  },
  leftIconText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    minWidth: 42,
  },
  rightIconText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.accent,
    textTransform: 'uppercase',
    paddingHorizontal: 4,
  },
  errorText: {
    color: theme.colors.alert,
    fontSize: 11,
    fontFamily: theme.fonts.semiBold,
    marginTop: 2,
  },
  globalErrorText: {
    color: theme.colors.alert,
    fontSize: 12,
    fontFamily: theme.fonts.bold,
    textAlign: 'center',
    backgroundColor: theme.colors.alertBg,
    borderColor: '#FEC2C2',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    lineHeight: 18,
  },
  // 4. Sign-In Button
  submitButton: {
    height: 52, 
    backgroundColor: theme.colors.primary, 
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
    marginTop: 8,
  },
  submitButtonText: {
    color: theme.colors.white,
    fontSize: 13,
    fontFamily: theme.fonts.bold,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  // Placeholder card for OTP / BILLING ID
  infoCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 20,
    alignItems: 'center',
    gap: 8,
  },
  infoCardTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.primary,
    textTransform: 'uppercase',
  },
  infoCardText: {
    fontSize: 12,
    color: theme.colors.textMuted,
    textAlign: 'center',
    lineHeight: 18,
  },
  // 5. Registration Footer
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F0F4F8',
    gap: 4,
  },
  footerText: {
    fontSize: 13,
    fontFamily: theme.fonts.regular,
    color: theme.colors.textMuted,
  },
  footerLink: {
    fontSize: 13,
    fontFamily: theme.fonts.bold,
    color: theme.colors.accent,
  },
  qrScanButton: {
    height: 52,
    backgroundColor: theme.colors.accent, 
    borderRadius: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrScanButtonText: {
    color: theme.colors.white,
    fontSize: 11,
    fontFamily: theme.fonts.bold,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  billingGuideBox: {
    height: 52,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  billingGuideText: {
    fontSize: 11,
    color: theme.colors.textMuted,
    lineHeight: 16,
    textAlign: 'center',
  },
  supportText: {
    fontSize: 11,
    color: theme.colors.textMuted,
    textAlign: 'center',
    marginTop: 20,
    fontWeight: '500',
    fontFamily: 'GeistMono-Regular',
  }
});
