import React from 'react';
import {
  Activity,
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowRight,
  Bell,
  BellOff,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleUserRound,
  ClipboardList,
  Clock,
  Coins,
  Droplets,
  FileText,
  FlaskConical,
  Gauge,
  Hammer,
  Headset,
  Home,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Megaphone,
  MessagesSquare,
  Phone,
  Receipt,
  ScanLine,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Ticket,
  TriangleAlert,
  UserPlus,
  Wrench,
  X,
  XCircle,
  Zap,
} from 'lucide-react-native';

/**
 * Central icon component. Maps the legacy Ionicons name strings (used
 * throughout the app's config maps) to Lucide components so the app
 * matches the aquatrack-web Lucide iconography. API is drop-in
 * compatible with <AppIcon name size color style />.
 */
const ICON_MAP = {
  'alert-circle-outline': AlertCircle,
  'archive-outline': Archive,
  'arrow-back': ArrowLeft,
  'arrow-forward': ArrowRight,
  'business-outline': Building2,
  call: Phone,
  'call-outline': Phone,
  chatbubbles: MessagesSquare,
  'chatbubbles-outline': MessagesSquare,
  checkmark: Check,
  'checkmark-circle': CheckCircle2,
  'checkmark-circle-outline': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-forward': ChevronRight,
  'chevron-up': ChevronUp,
  'clipboard-outline': ClipboardList,
  close: X,
  'close-circle': XCircle,
  construct: Wrench,
  'construct-outline': Wrench,
  'document-text': FileText,
  'document-text-outline': FileText,
  'flash-outline': Zap,
  flask: FlaskConical,
  headset: Headset,
  home: Home,
  'home-outline': Home,
  'location-outline': MapPin,
  'lock-closed-outline': Lock,
  'log-in-outline': LogIn,
  'log-out-outline': LogOut,
  'mail-outline': Mail,
  megaphone: Megaphone,
  'megaphone-outline': Megaphone,
  notifications: Bell,
  'notifications-off-outline': BellOff,
  'notifications-outline': Bell,
  person: CircleUserRound,
  'person-add-outline': UserPlus,
  'person-outline': CircleUserRound,
  pulse: Activity,
  'pulse-outline': Activity,
  'receipt-outline': Receipt,
  'scan-outline': ScanLine,
  search: Search,
  'search-outline': Search,
  'settings-outline': Settings,
  'settings-sharp': Settings,
  'shield-checkmark': ShieldCheck,
  'shield-outline': Shield,
  sparkles: Sparkles,
  ticket: Ticket,
  'ticket-outline': Ticket,
  warning: TriangleAlert,
  'warning-outline': TriangleAlert,
  water: Droplets,
  'water-outline': Droplets,
  build: Hammer,
  'build-outline': Hammer,
  speedometer: Gauge,
  cash: Coins,
  'time-outline': Clock,
  'paper-plane-outline': Send,
};

export default function AppIcon({ name, ...props }) {
  const Icon = ICON_MAP[name] || AlertCircle;
  return <Icon {...props} />;
}