import { StyleSheet } from 'react-native';
import { theme } from '../../src/config/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContainer: {
    padding: 16,
    paddingBottom: 110,
  },
  header: {
    marginBottom: 16,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.colors.primary,
  },
  subtitle: {
    fontSize: 12,
    color: theme.colors.textMuted,
    marginTop: 2,
  },
  card: {
    backgroundColor: theme.colors.white,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: 20,
    marginBottom: 16,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: '900',
    color: theme.colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.border,
    paddingBottom: 8,
  },
  // Form Fields
  form: {
    gap: 14,
  },
  label: {
    fontSize: 9,
    fontWeight: '900',
    color: theme.colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  textArea: {
    borderWidth: 1,
    borderColor: '#D0D7E2',
    borderRadius: 12,
    padding: 14,
    fontSize: 14,
    fontWeight: '500',
    color: theme.colors.primary,
    backgroundColor: theme.colors.white,
    height: 100,
    textAlignVertical: 'top',
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: '#D0D7E2',
    borderRadius: 12,
    backgroundColor: theme.colors.white,
    height: 52,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  pickerSelect: {
    color: theme.colors.primary,
    fontSize: 14,
  },
  // Location HUD & Map
  mapContainer: {
    height: 200,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginVertical: 12,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  locationButton: {
    height: 48,
    backgroundColor: theme.colors.primary,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 4,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  locationButtonText: {
    color: theme.colors.white,
    fontSize: 13,
    fontWeight: 'bold',
  },
  locationStatus: {
    marginTop: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#F0F4F8',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  locationStatusText: {
    fontSize: 12,
    color: theme.colors.primary,
    lineHeight: 18,
  },
  locationStatusLabel: {
    fontWeight: '800',
  },
  // Image Upload style
  imagePickerBtn: {
    height: 50,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: theme.colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 159, 222, 0.05)',
  },
  imagePickerText: {
    color: theme.colors.accent,
    fontSize: 13,
    fontWeight: 'bold',
  },
  previewImage: {
    width: '100%',
    height: 180,
    borderRadius: 12,
    resizeMode: 'cover',
    marginTop: 8,
  },
  // AI Diagnostics
  aiCard: {
    backgroundColor: '#EFF6FF',
    borderColor: '#BFDBFE',
    borderWidth: 1,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
  },
  aiTitle: {
    fontSize: 11,
    fontWeight: '900',
    color: theme.colors.accent,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  aiDetailRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  aiDetailLabel: {
    width: 90,
    fontSize: 11,
    fontWeight: '800',
    color: '#1E40AF',
  },
  aiDetailValue: {
    flex: 1,
    fontSize: 11,
    color: '#1E3A8A',
    lineHeight: 15,
  },
  // Geofence Out-Of-Scope Alerts
  geofenceWarning: {
    backgroundColor: theme.colors.alertBg,
    borderColor: '#FEC2C2',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginVertical: 8,
  },
  geofenceWarningText: {
    color: theme.colors.alert,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 16,
  },
  // Submit btn
  // Submit Status Indicator
  statusIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
    borderRadius: 12,
    marginTop: 8,
  },
  statusIndicatorText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1D4ED8',
  },
  // Submit Button
  submitBtn: {
    height: 52,
    backgroundColor: theme.colors.primary,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 16,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  submitBtnDisabled: {
    backgroundColor: theme.colors.border,
  },
  submitBtnText: {
    color: theme.colors.white,
    fontSize: 13,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
  }
});
